import { db } from '@/firebase'
import { doc, setDoc } from 'firebase/firestore'
import React from 'react'

export default function Test() {
  var data3 = [
    'Lactose',
    'Gluten',
    'Lupin',
    'Celery',
    'Crustaceans',
    'Eggs',
    'Fish',
    'Molluscs',
    'Mustard',
    'Nuts',
    'Peanuts',
    'Seasme Seeds',
    'Soy',
    'Sulphite',
  ]

  const set2 = () => {
    data3.forEach(async (e) => {
      try {
        await setDoc(doc(db,"Allergy_Data",e),{
          Name: e
        })
      } catch (e) {}
    })
  }

  const set = () => {
    data.forEach(async (e, index) => {
      try {
        await setDoc(doc(db, 'Disease_Data', e.Disease), {
          Disease: e.Disease,
          Calcium: e.Calcium,
          Iron: e.Iron,
          Sodium: e.Sodium,
          VitaminA: e.VitaminA,
          VitaminC: e.VitaminC,
          Cholesterol: e.Cholesterol,
          Saturated_fat: e.Saturated_fat,
          Protein: e.Protein,
          Carbohydrate: e.Carbohydrate,
          Energy: e.Energy,
          Sugars: e.Sugars,
          Fiber: e.Fiber,
          Potassium: e.Potassium,
          Total_Trans: e.Total_Trans,
          Total_Lipid: e.Total_Lipid,
        })
      } catch (e) {
        console.log(e.message)
      }
    })
    console.log('done')
  }

  return (
    <button
      onClick={() => {
        set2()
      }}
    >
      Test
    </button>
  )
}

const data = [
  {
    Disease: 'Obesity',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 22.0,
    Protein: 0.0,
    Carbohydrate: 225,
    Energy: 0,
    Sugars: 25.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Type 2 diabetes',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 15.0,
    Protein: 0.0,
    Carbohydrate: 130,
    Energy: 0,
    Sugars: 25.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Cardiovascular disease',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 2.3,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.3,
    Saturated_fat: 15.5,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 25.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'High blood pressure',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 1.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 16.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Cancer',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 21.5,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Osteoporosis',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 1.5,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Non-alcoholic fatty liver disease',
    Calcium: 0.6,
    Iron: 0.0,
    Sodium: 1.2,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 20.0,
    Protein: 0.0,
    Carbohydrate: 420,
    Energy: 0,
    Sugars: 30.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Metabolic syndrome',
    Calcium: 0.6,
    Iron: 0.017,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 30.0,
    Protein: 60.0,
    Carbohydrate: 555,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Gout',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 1.5,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 45.0,
    Carbohydrate: 350,
    Energy: 0,
    Sugars: 20.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Rheumatoid arthritis',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 22.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Multiple sclerosis',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 15.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: "Crohn's disease",
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 1.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 20.0,
    Protein: 40.0,
    Carbohydrate: 260,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 23.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.4,
  },
  {
    Disease: 'Hepatitis',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 23.4,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Gallbladder disease',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 21.5,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Kidney disease',
    Calcium: 1.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 48.75,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 3.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: "Alzheimer's disease",
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 32.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: "Parkinson's disease",
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 30.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Autism',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 23.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Acne',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 24.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Asthma',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 1.5,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Respiratory infections',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 1.8,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Chronic fatigue syndrome',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 23.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Insomnia',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 3.5,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Premenstrual syndrome',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 4.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Polycystic ovary syndrome',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 325,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Erectile dysfunction',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 15.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 2.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Prostate cancer',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 15.5,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 2.2,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Breast cancer',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 20.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Lung cancer',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 1.7,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 23.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Pancreatic cancer',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 20.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Ovarian cancer',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 22.22,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 2.1,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Endometrial cancer',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 13.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Bladder cancer',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 21.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Kidney cancer',
    Calcium: 0.5,
    Iron: 0.017,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 337,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 4.6,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Melanoma',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 30.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Liver cancer',
    Calcium: 0.0,
    Iron: 10.0,
    Sodium: 1.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 20.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 24.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'High cholesterol',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.2,
    Saturated_fat: 13.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.1,
    Total_Lipid: 0.3,
  },
  {
    Disease: 'Diarrhea',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 0.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 20.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Shortness of breath',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 2.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 22.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 25.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'low blood pressure',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 21.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 20.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'Stomach cramps',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 44.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
  {
    Disease: 'nausea',
    Calcium: 0.0,
    Iron: 0.0,
    Sodium: 0.0,
    VitaminA: 0,
    VitaminC: 0,
    Cholesterol: 0.0,
    Saturated_fat: 16.0,
    Protein: 0.0,
    Carbohydrate: 0,
    Energy: 0,
    Sugars: 0.0,
    Fiber: 0.0,
    Potassium: 0.0,
    Total_Trans: 0.0,
    Total_Lipid: 0.0,
  },
]
