import UserContext from "@/components/context/userContext";
import Testimonials from "components/Carousel";
import Carousel from "components/Carousel";
import Footer from "components/footer";
import Navbar from "components/header/navbar";
import Head from "next/head";
import Link from "next/link";
import { useContext } from "react";
import Swiper from "swiper";

export default function Index() {
  const u = useContext(UserContext);
  return (
    <>
      <Head>
        <title>Eat Smart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      {/* <Nav/> */}

      <div style={{ backgroundColor: "#f7fafc" }}>
        <div className="p-4">
          <Testimonials />
        </div>
      </div>
    </>
  );
}

{
  /* <div>
        <div class="relative py-16 bg-gradient-to-br from-sky-50 to-gray-200">
          <div class="relative container m-auto px-6 text-gray-500 md:px-12 xl:px-40">
            <div class="m-auto md:w-8/12 lg:w-6/12 xl:w-6/12">
              <div class="rounded-xl bg-white shadow-xl">
                <div class="p-6 sm:p-16">
                  <div class="space-y-4">
                    <img
                      src="https://tailus.io/sources/blocks/social/preview/images/icon.svg"
                      // loading="lazy"
                      class="w-10"
                      alt="tailus logo"
                    />
                    <div class="mb-8 text-2xl text-cyan-900 font-bold">
                      {u ? "You are already Logged In" : "Log In To Continue"}
                      <h1 className="mt-3"> </h1>
                    </div>
                  </div>
                  {u ? (
                    <button
                      class="group h-12 px-6 border-2 border-gray-300 rounded-full transition duration-300 
 hover:border-blue-400 focus:bg-blue-50 active:bg-blue-100"
                    >
                      <div class="relative flex items-center space-x-4 justify-center">
                        <Link href="/bmi">
                          <span class="block w-max font-semibold tracking-wide text-gray-700 text-sm transition duration-300 group-hover:text-blue-600 sm:text-base">
                            Proceed
                          </span>
                        </Link>
                      </div>
                    </button>
                  ) : (
                    <div class="mt-16 grid space-y-4">
                      <button
                        class="group h-12 px-6 border-2 border-gray-300 rounded-full transition duration-300 
 hover:border-blue-400 focus:bg-blue-50 active:bg-blue-100"
                      >
                        <div class="relative flex items-center space-x-4 justify-center">
                          <img
                            src="https://tailus.io/sources/blocks/social/preview/images/google.svg"
                            class="absolute left-0 w-5"
                            alt="google logo"
                          />
                          <Link href="/">
                            <span class="block w-max font-semibold tracking-wide text-gray-700 text-sm transition duration-300 group-hover:text-blue-600 sm:text-base">
                              Continue with Google
                            </span>
                          </Link>
                        </div>
                      </button>
                      <button
                        class="group h-12 px-6 border-2 border-gray-300 rounded-full transition duration-300 
 hover:border-blue-400 focus:bg-blue-50 active:bg-blue-100"
                      >
                        <div class="relative flex items-center space-x-4 justify-center">
                          <img
                            src="https://firebasestorage.googleapis.com/v0/b/eat-smartz.appspot.com/o/WhatsApp%20Image%202023-01-26%20at%2016.39.40.jpg?alt=media&token=2bfa1a0e-248d-4aa2-bed8-fb49d75d451e"
                            class="absolute left-0 w-5"
                            alt="Facebook logo"
                          />
                          <Link href="/login">
                            <span class="block w-max font-semibold tracking-wide text-gray-700 text-sm transition duration-300 group-hover:text-blue-600 sm:text-base">
                              Continue with Email and Password
                            </span>
                          </Link>
                        </div>
                      </button>

                      <button
                        class="group h-12 px-6 border-2 border-gray-300 rounded-full transition duration-300 
                                     hover:border-blue-400 focus:bg-blue-50 active:bg-blue-100"
                      >
                        <div class="relative flex items-center space-x-4 justify-center">
                          <img
                            src="https://firebasestorage.googleapis.com/v0/b/eat-smartz.appspot.com/o/WhatsApp%20Image%202023-01-26%20at%2016.51.22.jpg?alt=media&token=8deee800-3e65-4c0c-8f6c-7bb865ee1600"
                            class="absolute left-0 w-5"
                            alt="Facebook logo"
                          />

                          <Link href="/register">
                            <span class="block w-max font-semibold tracking-wide text-gray-700 text-sm transition duration-300 group-hover:text-blue-600 sm:text-base">
                              Sign Up for a new Account
                            </span>
                          </Link>
                        </div>
                      </button>

                      <button
                        class="group h-12 px-6 border-2 border-gray-300 rounded-full transition duration-300 
                                     hover:border-blue-400 focus:bg-blue-50 active:bg-blue-100"
                      >
                        <div class="relative flex items-center space-x-4 justify-center">
                          <img
                            src="https://firebasestorage.googleapis.com/v0/b/eat-smartz.appspot.com/o/WhatsApp%20Image%202023-01-26%20at%2016.34.35.jpg?alt=media&token=2a1db796-cf53-49b2-86e3-212c21a75f0b"
                            class="absolute left-0 w-5"
                            alt="Facebook logo"
                          />

                          <Link href="/foodCheck">
                            <span class="block w-max font-semibold tracking-wide text-gray-700 text-sm transition duration-300 group-hover:text-blue-600 sm:text-base">
                              Continue as Guest
                            </span>
                          </Link>
                        </div>
                      </button>
                    </div>
                  )}

                  <div class="mt-16 space-y-4 text-gray-600 text-center sm:-mb-8">
                    <p class="text-xs">
                      By proceeding, you agree to our{" "}
                      <a href="#" class="underline">
                        Terms of Use
                      </a>{" "}
                      and confirm you have read our{" "}
                      <a href="#" class="underline">
                        Privacy and Cookie Statement
                      </a>
                      .
                    </p>
                    <p class="text-xs">
                      This site is protected by reCAPTCHA and the{" "}
                      <a href="#" class="underline">
                        Google Privacy Policy
                      </a>{" "}
                      and{" "}
                      <a href="#" class="underline">
                        Terms of Service
                      </a>{" "}
                      apply.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div> */
}
